version: "3.9"

services:
  basic-node-rabbitmq:
    image: rabbitmq:3-management
    container_name: basic-node-rabbitmq
    ports:
      - "5673:5672"  # Changed left port to avoid conflict with old project
      - "15673:15672" # Changed left port to avoid conflict with old project
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mongo-cluster

  basic-node-express:
    build: .
    depends_on:
      basic-node-rabbitmq:
       condition: service_healthy
    env_file:
      - .env
    ports:
      - "4002:4000" # Changed left port to avoid conflict with old project
    volumes:
      - .:/app
    command: npm run dev
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    external: true

