version: "3.9"

services:

  node-app:
    build: .
    container_name: test-node
    env_file:
      - .env
    ports:
      - "4012:4000"
    volumes:
      - .:/app
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    external: true  
