version: "3.9"

services:
  basic-node-rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmd-basic-node
    ports:
      - "5673:5672"  # Changed left port to avoid conflict with old project
      - "15673:15672" # Changed left port to avoid conflict with old project
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}


  basic-node-express:
    build: .
    depends_on:
      - basic-node-rabbitmq
    env_file:
      - .env
    ports:
      - "4001:4000" # Changed left port to avoid conflict with old project
    volumes:
      - .:/app
    command: npm run dev

volumes:
  pgdata: {}
